name: Canary Release

on:
  push:
    branches:
      - main
    paths:
      - src/**

permissions:
  contents: write

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install -p
      - name: Set Canary Version
        run: |
          sed -Ei '/"version"/s/"([0-9]+\.)+[0-9]+"/"canary-${{ github.sha }}"/' package.json
      - name: Build with Bun
        run: bun run build --sourcemap=none
      - name: Zip for Canary Release
        working-directory: ./build
        run: zip -r ../scouter.zip .
      - name: Canary Release
        uses: softprops/action-gh-release@v2
        with:
          files: scouter.zip
          prerelease: true
          name: Canary build (latest commit)
          tag_name: canary
          body: |
            This release corresponds to the commit [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})