name: Main

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: bun install -p
      - name: Build with Bun
        run: bun run build --sourcemap=none
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Zip for Canary Release
        working-directory: ./build
        run: zip -r ../scouter.zip .
      - name: Canary Release
        uses: softprops/action-gh-release@v2
        with:
          files: scouter.zip
          prerelease: true
          name: Canary build (latest commit)
          tag_name: canary
          body: |
            This release corresponds to the commit `[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})`
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4