name: Release

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/release.yml

permissions:
  contents: write
  pages: write

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.get-new-version.outputs.new_version }}
      old_version: ${{ steps.get-old-version.outputs.old_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get New Version
        id: get-new-version
        run: |
          version=$(sed -En '/version/s/^.*"(([0-9]+\.)+[0-9]+)".*$/\1/p' package.json)
          echo "new_version=v$version" >> "$GITHUB_OUTPUT"
      - name: Get Old Version
        id: get-old-version
        run: |
          version=$(git describe --abbrev=0 --tags)
          echo "old_version=$version" >> "$GITHUB_OUTPUT"
  build:
    needs: versions
    runs-on: ubuntu-latest
    if: needs.versions.outputs.new_version != needs.versions.outputs.old_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: bun install -p
      - name: Build with Bun
        run: bun run build --sourcemap=none
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Zip for Release
        working-directory: ./build
        run: zip -r ../scouter.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: scouter.zip
          make_latest: true
          tag_name: ${{ needs.versions.outputs.new_version }}
          body: |
            Try the app: https://ant-throw-pology.github.io/2898-scouter
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4