name: Release

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: New Version
        required: true
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set Version
        run: |
          echo "${{ inputs.new_version }}" | grep -Eq '^([0-9]+\.)+[0-9]+$' && sed -Ei '/"version"/s/"([0-9]+\.)+[0-9]+"/"${{ inputs.new_version }}"/' package.json
      - name: Commit Version
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: v${{ inputs.new_version }}
  
  build:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: bun install -p
      - name: Build with Bun
        run: bun run build --sourcemap=none
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Zip for Release
        working-directory: ./build
        run: zip -r ../scouter.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: scouter.zip
          draft: true
          tag_name: v${{ inputs.new_version }}
          body: |
            Try the app: https://ant-throw-pology.github.io/2898-scouter
          generate_release_notes: true
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4